- page: beetleweight
  images:
    - title: Milled Aluminum Front Panel
      url: /images/beetleweight/beetle-front-panel.JPG
      caption: This was done on a Haas MiniMill at my school's machine shop and it took about 2 hours with several fixturing setups.
    - title: UHMW Side Rails
      url: /images/beetleweight/uhmw-rails.jpg
      caption: The UHMW side rails were also machined on the mill.
    - title: Chassis Mock-up
      url: /images/beetleweight/beetle-mockup.jpg
      caption: A mock-up of the basic chassis of the robot.
    - title: Electronics Bay
      url: /images/beetleweight/beetle-electronics.jpg
      caption: Some tight tolerances with the electronics bay! Not pictured is the battery and the rest of the control electronic components.
    - title: Almost Final Mock-up
      url: /images/beetleweight/beetle-almost.JPG
      caption: We're getting there! Just needs some TPU spacers.